version: "3.8"

networks:
   frontend:
   backend:

services:
   catalog:
      build:
         context: .\src\Services\ProductCatalogApi
         dockerfile: Dockerfile
      image: product/catalog
      environment:
         - DatabaseServer=mssqlserver
         - DatabaseName=ProductDb
         - DatabaseUser=sa
         - DatabaseUserPassword=Spokie@500
      container_name: productapi
      ports:
         - "5000:80"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver
         
   mssqlserver:
      image: "microsoft/mssql-server-linux:latest"
      ports:
         - "1445:1433"

      container_name: mssqlcontainer
      environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=Spokie@500
      networks:
         - backend